version: '3.3'

services:
  mysql_db:
    image: mysql
    cap_add:
      - SYS_NICE
    container_name: mysql-server-container
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
    # port mapping
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
      - app-tier
    volumes:
      - db_data:/var/lib/mysql
      - "mysql_grant_permission.sql:/docker-entrypoint-initdb.d/1.sql"

  phpmyadmin:
    container_name: mysql-php-admin
    depends_on:
      - mysql_db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8088:80
    environment:
      PMA_HOST: mysql_db
      MYSQL_ROOT_PASSWORD: 123

  voucher_app:
    container_name: voucher-python-app
    build:
      context: .
      dockerfile: docker_voucher/Dockerfile
    depends_on:
      - mysql_db
    links:
      - mysql_db
    networks:
      - app-tier

  api_app:
    container_name: fastapi-python-app
    build:
      context: .
      dockerfile: docker_api/Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      - mysql_db
    links:
      - mysql_db
    networks:
      - app-tier

#  api_app:
#    build: .
#    container_name: fastapi-python-app
#    command: sh run_apps.sh

#volumes:
#  mysql_grant_permission.sql:
#  mysql-data:
networks:
  app-tier:
    driver: bridge

volumes:
  db_data:
  mysql_grant_permission.sql: