# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Voucher(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, vocher_amount: int=None):  # noqa: E501
        """Voucher - a model defined in Swagger

        :param vocher_amount: The vocher_amount of this Voucher.  # noqa: E501
        :type vocher_amount: int
        """
        self.swagger_types = {
            'vocher_amount': int
        }

        self.attribute_map = {
            'vocher_amount': 'vocher_amount'
        }
        self._vocher_amount = vocher_amount

    @classmethod
    def from_dict(cls, dikt) -> 'Voucher':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Voucher of this Voucher.  # noqa: E501
        :rtype: Voucher
        """
        return util.deserialize_model(dikt, cls)

    @property
    def vocher_amount(self) -> int:
        """Gets the vocher_amount of this Voucher.


        :return: The vocher_amount of this Voucher.
        :rtype: int
        """
        return self._vocher_amount

    @vocher_amount.setter
    def vocher_amount(self, vocher_amount: int):
        """Sets the vocher_amount of this Voucher.


        :param vocher_amount: The vocher_amount of this Voucher.
        :type vocher_amount: int
        """

        self._vocher_amount = vocher_amount
